### PR TITLE
GL: Missing precision qualifier for floats in bump map calc

### PR DESCRIPTION
**Pull request by flyinghead**
Fixes the GLSL error in Dolphin Blue

### CODE REVIEW

**Comment by inactive123** [comment]
Thanks!

**Comment by inactive123** [comment]
Should this also be done for the OIT renderer?

**Comment by flyinghead** [comment]
No this is only for GLES

**Comment by blisstik** [comment]
Hey guys, new issue with 955533a on ARM XU4. When exiting RA, it hangs on whatever screen I'm on. The last line of the log may help: `Waiting for emu thread...`

Edit: this happens with the "Threading rendering" turned on.

```
Parameters: 
Executing: /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-reicast/reicast_libretro.so --config /opt/retropie/configs/dreamcast/retroarch.cfg "/home/pigaming/RetroPie/roms/dreamcast/Dolphin Blue.lst" --appendconfig /dev/shm/retroarch.cfg
[reicast]: Got size: 640 x 480.
Creating dir: /home/pigaming/RetroPie/BIOS/dc/data
context_reset.
ARM VFP-Run Fast (NFP) enabled !
Linux paging: 00001000 00001000 00000FFF
MAP 00800000 w/ 50331648
MAP 20000000 w/ 50331648
MAP 04000000 w/ 33554432
MAP 06000000 w/ 33554432
MAP 0C000000 w/ 0
A8
vmem reserve: base: 80F00000, aram: a0f00000, vram: 84F00000, ram: 8CF00000
Resetting mem
Mem alloc successful!Loaded /home/pigaming/RetroPie/BIOS/dc/naomi_boot.bin as bootrom

Sh4 Reset
recSh4 Init
Freeing fpcb
readm helpers: up to B1C49250
nullDC-Naomi rom loader v1.2
File: /home/pigaming/RetroPie/roms/dreamcast/Dolphin Blue.lst
+Loading naomi rom : Dolphin Blue
+1 romfiles, 128.00 MB set size, 128.00 MB set address space
+Mapping ROM

Mapped ROM Successfully !

EEPROM file : /home/pigaming/RetroPie/roms/dreamcast/Dolphin Blue.lst.eeprom

	 ARM7_TCB addr: 0xb1b07000 | from: 0xb1b064c8 | addr here: 0xb1ace004
Sh4 Reset
reios: IP.bin is ''
reios: Hardware ID is: 
reios: Maker ID is:    
reios: Device info is: 
reios: Area symbols is: 
reios: Peripherals is: 
reios: Product number is: 
reios: Product version is: 
reios: Release date is: 
reios: Boot filename is: 
reios: Software company is: 
reios: Software name is: 
reios: loading ip.bin from FAD: 0
reios: bootfile is ''
Get MemPtr unsupported area : addr=0xA0000000
Get MemPtr unsupported area : addr=0xA0000018
Freeing fpcb
Get MemPtr unsupported area : addr=0x80000080
sh4io: Const write ignored @@ 00000028 <- FFFFA400
Get MemPtr unsupported area : addr=0x800000A8
Get MemPtr unsupported area : addr=0x800000BE
Get MemPtr unsupported area : addr=0x800000C6
Freeing fpcb
Get MemPtr unsupported area : addr=0xA0000420
Get MemPtr unsupported area : addr=0xA0000440
sh4io: Const write ignored @@ 00000028 <- 00000000
Get MemPtr unsupported area : addr=0xA00004BC
sh4io: Const write ignored @@ 00000028 <- 00000000
Get MemPtr unsupported area : addr=0xA0000506
Get MemPtr unsupported area : addr=0xA000057C
Get MemPtr unsupported area : addr=0xA0000586
Get MemPtr unsupported area : addr=0xA000058E
Get MemPtr unsupported area : addr=0xA00005A6
Get MemPtr unsupported area : addr=0xA00005AC
Get MemPtr unsupported area : addr=0xA00005B8
Get MemPtr unsupported area : addr=0xA00005CE
naomi?WTF? WriteMem: 5F7070 <= 7, 4
naomi?WTF? WriteMem: 5F7074 <= 0, 4
naomi?WTF? WriteMem: 5F7070 <= 7, 4
naomi?WTF? ReadMem: 5F7074, 4
naomi?WTF? WriteMem: 5F7070 <= 7, 4
naomi?WTF? WriteMem: 5F7074 <= 1, 4
naomi?WTF? WriteMem: 5F7070 <= 7, 4
naomi?WTF? ReadMem: 5F7074, 4
unknown MAPLE Frame
Unknown 0x86 : SubCommand 0x1 - State: Cmd 0x0 Mode :  0x0 Node : 0x0
Command : 0x86,Data : 4 bytes
00000001 
new tactx
new tactx
Unknown 0x86 : SubCommand 0x13 - State: Cmd 0x14 Mode :  0x0 Node : 0x1
Command : 0x86,Data : 12 bytes
20070113 02210202 00000422 
naomi?WTF? WriteMem: 5F705C <= 4, 4
naomi?WTF? WriteMem: 5F705C <= 4, 4
naomi?WTF? WriteMem: 5F705C <= 4, 4
naomi?WTF? WriteMem: 5F705C <= 4, 4
naomi?WTF? WriteMem: 5F705C <= 4, 4
naomi?WTF? WriteMem: 5F705C <= 4, 4
Waiting for emu thread...
```

**Comment by flyinghead** [comment]
This is a known issue.
It happens if you unload the core or exit RA while no frame is being rendered. However it could happen more or less often depending on the OS.

**Pull request merged**
