### PR TITLE
fix cpu unthrottling

### PR DESCRIPTION
**Pull request by RetroSven**

### CODE REVIEW

**Comment by inactive123** [comment]
@RetroSven Is it correct that I can no longer fastforward now even with non-threaded rendering? Certainly appears to be the case. That is bad.

**Comment by inactive123** [comment]
Methinks you should make all of this optional and only enable it when threaded rendering is enabled, we don't want all this code active for non-threaded rendering, we want to go back to the simple way of doing audio like before for non-threaded rendering.

Also, make sure that you can still fastforward with threaded rendering as well.

**Comment by RetroSven** [comment]
I did want to make all of this optional via my earlier suggestion of making a RA config that pushes save states to the background.  We know that solution works and is not anywhere as invasive as all of these things I've been doing to the reicast code.  Seems like every time I fix something, some new problem takes its place.I strongly suggest you let me make this a RA config.

**Comment by RetroSven** [comment]
oh and btw  all of the changes I've made to reicast for this issue are only enabled when threaded rendering is enabled

**Comment by RetroSven** [comment]
scratch that - I just realized the newest addition with the ENV entry is not wrapped in ifdefs - but regardless, I'd prefer to remove all of the recent changes and just make a RA config

**Comment by RetroSven** [comment]
one more - if there are still problems after this, let's make it a RA config
https://github.com/libretro/reicast-emulator/pull/248

**Comment by inactive123** [comment]
No, I think it is the wrong approach entirely to start adding RetroArch features just to work around issues in specific cores. That should not really happen. It should be properly fixed in the core instead.

**Comment by RetroSven** [comment]
Then please provide details on how the core can be made aware that fast forwarding is enabled.

**Comment by RetroSven** [comment]
btw I'm already aware of how it "normally" works, but reicast's implementation is different - its timings are handled in a separate thread running outside of RA's main iterate loop

**Pull request merged**
