### PR TITLE
Run the emulator in its own thread and render on the main thread

### PR DESCRIPTION
**Pull request by flyinghead**
This can be enabled by a runtime setting if compiled with `NO_THREADS:=0`

### CODE REVIEW

**Comment by blisstik** [comment]
Latest commits crashes on ARM

```
Parameters: 
Executing: /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-reicast/reicast_libretro.so --config /opt/retropie/configs/dreamcast/retroarch.cfg "/home/pigaming/RetroPie/roms/dreamcast/Dolphin Blue.lst" --appendconfig /dev/shm/retroarch.cfg
[reicast]: Got size: 640 x 480.
Creating dir: /home/pigaming/RetroPie/BIOS/dc/data
context_reset.
ARM VFP-Run Fast (NFP) enabled !
Linux paging: 00001000 00001000 00000FFF
MAP 00800000 w/ 50331648
MAP 20000000 w/ 50331648
MAP 04000000 w/ 33554432
MAP 06000000 w/ 33554432
MAP 0C000000 w/ 0
A8
vmem reserve: base: 818A0000, aram: a18a0000, vram: 858A0000, ram: 8D8A0000
Resetting mem
Mem alloc successful!Loaded /home/pigaming/RetroPie/BIOS/dc/naomi_boot.bin as bootrom

Sh4 Reset
recSh4 Init
Freeing fpcb
readm helpers: up to B1C5D250
Shader: failed to compile 
0:99: S0032: no default precision defined for variable 's'
Shader linking: failed to link 
 (47 bytes), - Link failed because of invalid fragment shader. -
VERTEX:
#version 300 es 
#define TARGET_GL GLES3 
#define pp_Gouraud 0 
 
#define GLES2 0 
#define GLES3 1 
#define GL2 2 
#define GL3 3 
 
#if TARGET_GL == GL2 
#define highp 
#define lowp 
#define mediump 
#endif 
#if TARGET_GL == GLES2 || TARGET_GL == GL2 
#define in attribute 
#define out varying 
#endif 
 
 
#if TARGET_GL == GL3 || TARGET_GL == GLES3 
#if pp_Gouraud == 0 
#define INTERPOLATION flat 
#else 
#define INTERPOLATION smooth 
#endif 
#else 
#define INTERPOLATION 
#endif 

/* Vertex constants*/  
uniform highp vec4      scale; 
uniform highp vec4      depth_scale; 
/* Vertex input */ 
in highp vec4    in_pos; 
in lowp  vec4     in_base; 
in lowp vec4     in_offs; 
in mediump vec2  in_uv; 
/* output */ 
INTERPOLATION out lowp vec4 vtx_base; 
INTERPOLATION out lowp vec4 vtx_offs; 
              out mediump vec2 vtx_uv; 
void main() 
{ 
	vtx_base=in_base; 
	vtx_offs=in_offs; 
	vtx_uv=in_uv; 
	vec4 vpos=in_pos; 
#if TARGET_GL != GLES2 && TARGET_GL != GL2 
   if (isinf(vpos.z)) 
		vpos.w = 1.18e-38; 
	else 
#endif 
		vpos.w = 1.0 / vpos.z; 
#if TARGET_GL != GLES2 
   if (vpos.w < 0.0) { 
      gl_Position = vec4(0.0, 0.0, 0.0, vpos.w); 
         return; 
   } 
   vpos.z = vpos.w; 
#else 
   vpos.z=depth_scale.x+depth_scale.y*vpos.w;  
#endif 
	vpos.xy=vpos.xy*scale.xy-scale.zw;  
	vpos.xy*=vpos.w;  
	gl_Position = vpos; 
}
FRAGMENT:
#version 300 es 
#define TARGET_GL GLES3 

#define cp_AlphaTest 0 
#define pp_ClipTestMode -1 
#define pp_UseAlpha 0 
#define pp_Texture 1 
#define pp_IgnoreTexA 0 
#define pp_ShadInstr 0 
#define pp_Offset 0 
#define pp_FogCtrl 0 
#define pp_Gouraud 0 
#define pp_BumpMap 1 
#define PI 3.1415926 

#define GLES2 0 
#define GLES3 1 
#define GL2 2 
#define GL3 3 
 
#if TARGET_GL == GL2 
#define highp 
#define lowp 
#define mediump 
#endif 
#if TARGET_GL == GLES3 
out highp vec4 FragColor; 
#define gl_FragColor FragColor 
#define FOG_CHANNEL a 
#elif TARGET_GL == GL3 
out highp vec4 FragColor; 
#define gl_FragColor FragColor 
#define FOG_CHANNEL r 
#else 
#define in varying 
#define texture texture2D 
#define FOG_CHANNEL a 
#endif 
 
 
#if TARGET_GL == GL3 || TARGET_GL == GLES3 
#if pp_Gouraud == 0 
#define INTERPOLATION flat 
#else 
#define INTERPOLATION smooth 
#endif 
#else 
#define INTERPOLATION 
#endif 

/* Shader program params*/ 
/* gles has no alpha test stage, so its emulated on the shader */ 
uniform lowp float cp_AlphaTestValue; 
uniform lowp vec4 pp_ClipTest; 
uniform lowp vec3 sp_FOG_COL_RAM,sp_FOG_COL_VERT; 
uniform highp float sp_FOG_DENSITY; 
uniform sampler2D tex,fog_table; 
uniform lowp float trilinear_alpha; 
/* Vertex input*/ 
INTERPOLATION in lowp vec4 vtx_base; 
INTERPOLATION in lowp vec4 vtx_offs; 
in mediump vec2 vtx_uv; 
lowp float fog_mode2(highp float w) 
{ 
   highp float z   = clamp(w * sp_FOG_DENSITY, 1.0, 255.9999); 
   highp float exp = floor(log2(z)); 
   highp float m = z * 16.0 / pow(2.0, exp) - 16.0; 
   lowp float idx = floor(m) + exp * 16.0 + 0.5; 
   highp vec4 fog_coef = texture(fog_table, vec2(idx / 128.0, 0.75 - (m - floor(m)) / 2.0)); 
   return fog_coef.FOG_CHANNEL; 
} 
void main() 
{ 
	// Clip outside the box 
	#if pp_ClipTestMode==1 
		if (gl_FragCoord.x < pp_ClipTest.x || gl_FragCoord.x > pp_ClipTest.z 
				|| gl_FragCoord.y < pp_ClipTest.y || gl_FragCoord.y > pp_ClipTest.w) 
			discard; 
	#endif 
	// Clip inside the box 
	#if pp_ClipTestMode==-1 
		if (gl_FragCoord.x >= pp_ClipTest.x && gl_FragCoord.x <= pp_ClipTest.z 
				&& gl_FragCoord.y >= pp_ClipTest.y && gl_FragCoord.y <= pp_ClipTest.w) 
			discard; 
	#endif 
	
   lowp vec4 color=vtx_base; 
	#if pp_UseAlpha==0 
		color.a=1.0; 
	#endif
	#if pp_FogCtrl==3 
		color=vec4(sp_FOG_COL_RAM.rgb,fog_mode2(gl_FragCoord.w)); 
	#endif
	#if pp_Texture==1 
	{ 
      lowp vec4 texcol=texture(tex, vtx_uv); 
		 
		#if pp_BumpMap == 1 
			float s = PI / 2.0 * (texcol.a * 15.0 * 16.0 + texcol.r * 15.0) / 255.0; 
			float r = 2.0 * PI * (texcol.g * 15.0 * 16.0 + texcol.b * 15.0) / 255.0; 
			texcol.a = clamp(vtx_offs.a + vtx_offs.r * sin(s) + vtx_offs.g * cos(s) * cos(r - 2.0 * PI * vtx_offs.b), 0.0, 1.0); 
			texcol.rgb = vec3(1.0, 1.0, 1.0);	 
		#else
			#if pp_IgnoreTexA==1 
				texcol.a=1.0;	 
			#endif
         color *= trilinear_alpha; 
			
			#if cp_AlphaTest == 1 
				if (cp_AlphaTestValue>texcol.a) discard;
			#endif  
		#endif 
      #if pp_ShadInstr==0 
      { 
         color=texcol; 
      } 
      #endif
		#if pp_ShadInstr==1 
		{ 
			color.rgb*=texcol.rgb; 
			color.a=texcol.a; 
		} 
		#endif
		#if pp_ShadInstr==2 
		{ 
			color.rgb=mix(color.rgb,texcol.rgb,texcol.a); 
		} 
		#endif
		#if  pp_ShadInstr==3 
		{ 
			color*=texcol; 
		} 
		#endif
		
		#if pp_Offset==1 && pp_BumpMap == 0 
		{ 
			color.rgb+=vtx_offs.rgb; 
			if (pp_FogCtrl==1) 
				color.rgb=mix(color.rgb,sp_FOG_COL_VERT.rgb,vtx_offs.a); 
		} 
		#endif
	} 
	#endif
	#if pp_FogCtrl==0 
	{ 
		color.rgb=mix(color.rgb,sp_FOG_COL_RAM.rgb,fog_mode2(gl_FragCoord.w));  
	} 
	#endif
	#if cp_AlphaTest == 1 
      color.a=1.0; 
	#endif  
   //color.rgb=vec3(gl_FragCoord.w * sp_FOG_DENSITY / 128.0);
#if TARGET_GL != GLES2 
	highp float w = gl_FragCoord.w * 100000.0; 
	gl_FragDepth = log2(1.0 + w) / 34.0; 
#endif 
   gl_FragColor =color; 
}
DEBUGBREAK!
SIGSEGV @ 0xb2df08b4 (signal_handler + 0x0x13f94b0) ... 0xb2df08b4 -> was not in vram
DEBUGBREAK!
/opt/retropie/supplementary/runcommand/runcommand.sh: line 1008:  3780 Illegal instruction     /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-reicast/reicast_libretro.so --config /opt/retropie/configs/dreamcast/retroarch.cfg "/home/pigaming/RetroPie/roms/dreamcast/Dolphin Blue.lst" --appendconfig /dev/shm/retroarch.cfg

```

**Comment by flyinghead** [comment]
Not related to this commit but I guess you tried Rayman 2?

**Comment by blisstik** [comment]
No, it's Dolphin Blue which has always worked. I archived the SO yesterday that worked and that one isn't working as well so I think it's an OS issue. Will report back.

**Comment by flyinghead** [comment]
Well actually it is a problem with the GLSL code: it's missing precision qualifiers in the Bump Map calculation section.
I thought Rayman 2 was the only game using bump mapping but I guess Dolphin Blue too?

This PR should fix the problem https://github.com/libretro/reicast-emulator/pull/212

**Comment by flyinghead** [comment]
Or perhaps it's just sending corrupted data to the GPU and it's random. I've seen many Naomi games do that.

**Comment by blisstik** [comment]
I'm sorry, its seems like its all the games. I don't even get to the boot logo.

**Comment by flyinghead** [comment]
Do you always see `#define pp_BumpMap 1 ` in the Fragment shader?

**Comment by blisstik** [comment]
I will check. I am reinstalling the OS as we speak and compiling now.

**Comment by blisstik** [comment]
On ARM XU4, just compiled to 955533a successfully. No issues and no #define pp_BumpMap 1

Is multithreading enabled by default on ARM now?

**Comment by flyinghead** [comment]
I believe it is compiled in but not enabled by default

**Comment by flyinghead** [comment]
There's a new core option "Threaded rendering" to enable it

**Comment by blisstik** [comment]
I see it, right above Purupuru Pack (restart). What is that one? LOL

**Comment by flyinghead** [comment]
https://segaretro.org/Jump_Pack

**Comment by blisstik** [comment]
The threaded rendering does make it smoother on XU4. There is still some audio glitches on Dolphin Blue. I've increased the buffer to 2048, no difference. Still a great update! Thank you!

**Pull request merged**
