### PR TITLE
Fix CHD Loading on rpi/armv7+ due to -O3 optimisations - fixes #816

### LINKED ISSUE #816: [RPi4] CHD loading broke.
On the previous public release of lakka it worked, and in the new public build chd files will not load. Retroarch just reboots when trying. This is not the same as the Naomi CHD "issue" #731 
I tested several games that were definitely loading and playing properly, but does not in the build that is in the new lakka release (2.3.2).
I will see if I can manage to get some helpful log later, and possibly pinpoint an earlier build where it stopped working.

### PR DESCRIPTION
**Pull request by joolswills**
Force -O2 optimisation for any targets with arm dynarec due to crashes with -O3 and CHD files on arm.

Set LDFLAGS to CFLAGS for rpi otherwise the CPU flags are not included at link time with LTO. This avoids armv6 code
being generated on Raspbian on armv7 when LTO is used.

### CODE REVIEW

**Comment by joolswills** [comment]
Feel free to implement this differently. I used the dynarec var as I couldn't think of a simpler way to group together arm targets.

**Comment by joolswills** [comment]
Also in the makefile the RZDCY logic looks unused - any reason I've missed why it's there?

**Comment by inactive123** [comment]
@flyinghead Requesting your feedback here.

**Comment by barbudreadmon** [comment]
Seems like a workaround that'll affect performances whatever the format instead of really fixing the issue ? If the issue is about being built with `-O3` on arm, i would expect it has something to do with alignment ? FWIW, using ubsan helped a lot with this kind of issue in FBNeo.

**Comment by flyinghead** [comment]
I wish I had a better solution but it's currently crashing all over the place on arm-based SBCs. 

(The RZDY stuff are remains from standalone flycast, no longer used it seems)

**Comment by MastaG** [comment]
I've still had to do a PR for the LDFLAGS that I had to send in.
Because also for ODroids, it will complain if the CFLAGS differ from LDFLAGS which will use the compilers default (which will obviously differ when running a generic arm distro).
I cant reproduce the crash on O3 since I only have a few Dreamcast dumps.

I guess we can push this, then I'll create separate PR or ODroid.

**Comment by joolswills** [comment]
@flyinghead I will recheck with your alignment fixes if it resolves this.

**Comment by joolswills** [comment]
I debugged the issue further. It seems caused by GCC optimising out some pointer references from what I can see in lzma_codec_init. I'll do some more debugging and post a backtrace if I get stuck

**Comment by joolswills** [comment]
I may be misinterpreting gdb though as it's not ideal debugging with optimisation on. It could still be lzma_fast_alloc as the error is still an alignment one related to this function.

**Comment by joolswills** [comment]
Looking at the code, another possibility may be undefined behaviour due to something similar to this:

https://wiki.sei.cmu.edu/confluence/plugins/servlet/mobile?contentId=87152059#content/view/87152059

**Comment by flyinghead** [comment]
The recent alignment fix in chd.c is only for 64-bit platforms. It was malloc'ing some memory, using the first 4 bytes to store some internal alloc id, and returning the rest of the buffer, which wasn't 8-byte aligned as required on 64-bit platforms.

So it shouldn't a problem on 32-bit platforms unless malloc returns memory that's not 4-byte aligned which is unlikely. I don't see other alignment requirements in the chd code.

**Comment by rtissera** [comment]
@flyinghead could you submit a PR to libchdr repository to fix this alignment issue ?
Would appreciate this a lot.

**Comment by flyinghead** [comment]
@rtissera See https://github.com/rtissera/libchdr/pull/20

**Comment by rtissera** [comment]
@flyinghead merged upstream, thanks !

**Comment by dankcushions** [comment]
closed during hack-gate 2020. @twinaphex please re-open :)

**Pull request closed without merging**
