### PR TITLE
build: removed vulkan requirement from unix platfrom.

### PR DESCRIPTION
**Pull request by dev-0x7C6**
I think this override should be removed.

### CODE REVIEW

**Comment by flyinghead** [comment]
What is the problem with this override? It should not require any header file or library from the toolchain

**Comment by dev-0x7C6** [comment]
Sorry for short description.

As I'm understanding the `unix` platform is a generic way to build this core on every unix distro.

For example adding overrides like `vulkan` always on or other similar stuff there is no guarantee that in future this pull some strings. Even from user perspective there is a need to read a bunch of script to find out that his flag is silently overwritten.

I'll share a bit more what's going from my perspective: 

I'm integrating this core in Yocto and I'm allowing to compile some cores with features based on machine capabilities or user feature requests. So if I specify that `vulkan` is optional feature this will be little lie for this core, because script force this anyway.

**Comment by dev-0x7C6** [comment]
Fixed typo in commit and PR

**Comment by flyinghead** [comment]
Defining HAVE_VULKAN=1 at compile time doesn't make Vulkan support a runtime requirement. This is controlled by retroarch or whatever frontend is being used. If the frontend doesn't support Vulkan, or if it's configured to use OpenGL, Vulkan code will not be run by flycast.

**Comment by dev-0x7C6** [comment]
Thanks for some clarification. I also take a quick look at code base in meantime. But I have still some questions.

> Defining HAVE_VULKAN=1 at compile time doesn't make Vulkan support a runtime requirement.

But this is enabling `vulcan` support in this core statically compile specific code into it and that may fail on some unix platforms. Am I right on that? or this just some wrapper to stream command to frontend? If there is always fine to have vulcan support even if platform is not supporting vulcan directly what is this flag supposed to do.

> This is controlled by retroarch or whatever frontend is being used.

Ok, good to know for sure, I was assuming that.

> If the frontend doesn't support Vulkan, or if it's configured to use OpenGL, Vulkan code will not be run by flycast.

If you're building and targeting platform unix (a whole bundle with retroarch and other cores). And that platform is not supporting `vulkan`, and `HAVE_VULKAN=1` always on that will leave dead code and rise memory consumption. Concept of having flag  `HAVE_VULKAN` will be wasted in that scenario.

**Comment by barbudreadmon** [comment]
You can disable the vulkan code by adding `HAVE_VULKAN=0` to the make command, i don't see any reason to make building without vulkan the default : 
- there is no need for external headers
- in 2020, gpus without vulkan support are becoming scarce, even SBCs from 2019 have vulkan-capable gpus
- vulkan is only enabled if retroarch is built with vulkan support & vulkan is set in video drivers

Furthermore, i don't want to tell everyone using this repo that they need to change their build script if they want vulkan support again, you'll have to change yours instead.

For all those reasons, i'll close.

**Comment by dev-0x7C6** [comment]
> You can disable the vulkan code by adding HAVE_VULKAN=0 to the make command, i don't see any reason to make building without vulkan the default

Well my bad then. I tested `make HAVE_VULKAN=0 platform=unix` and it's working. The problem was that I typed `HAVE_VULCAN` with typo probably... and I found that makefile scripts is setting this in unix platform witch made me too think that problem lies in makefile script.

@flyinghead Please accept my apologies for no understanding correctly how makefile overrides working.

> Furthermore, i don't want to tell everyone using this repo that they need to change their build script if they want vulkan support again, you'll have to change yours instead.

I found this makefile approach very painful for embedded system builders. There is too many things like guessing form `uname` and other stuff and this working strange in sandbox with cross-compiler. In my opinion there will be more problems with support newer unix platforms, maintain old ones, and adding proper support for 64bit platforms. Those makefiles growing in size and there will be always demand for new platforms. And as you stated this build script is not flexible, because any change can lead to broke someone else build setup.

In Yocto there is solution to manage platform features, machines and etc. Some of those features are perfect fit to cleanup platform burden. But Yocto is embedded system builder and unix oriented one, so the product is whole system image or docker images which will not cover typical compilation in debian or ubuntu environment and totally miss as custom platforms like ps4, wii or nintendo switch and etc.

Ah and yeah is there any documentation how to write makefiles for libretro project?

Anyway thanks for keeping good work.

**Pull request closed without merging**
