### PR TITLE
Support clang

### PR DESCRIPTION
**Pull request by MastaG**
Add a HAVE_CLANG option to build with clang and link with lld.
Also added a small buildfix to one the cpp.
@flyinghead please review.

There's one warning when building with clang.
warning: optimization flag '-frename-registers' is not supported [-Wignored-optimization-argument]

However the -frename-registers flag is all over the Makefile.
Putting that behind a ifeq clause will make the Makefile even messier.

So just live with the warning for now.

### CODE REVIEW

**Review by flyinghead — APPROVED** [review]

**Comment by MastaG** [comment]
Thanks for looking into this @flyinghead 
I've tested a gcc 9 build:
make platform=odroid BOARD=ODROID-XU3 ARCH=arm HAVE_CLANG=0 -j8
and clang 8.0 build:
make platform=odroid BOARD=ODROID-XU3 ARCH=arm HAVE_CLANG=1 -j8

They both run fine, so I can soon do some comparison between the two to see if there's any difference in performance.

I'm certain about the Makefile changes.
However I needed you to verify the change to core/rec-ARM/rec_arm.cpp, because clang was complaining about that one.

**Comment by barbudreadmon** [comment]
@MastaG Where did you get clang-8 for arm ? Did you build it yourself ? I couldn't find a `.deb` version for ubuntu 18.04 
On a sidenote, building yabasanshiro with clang-7 instead of clang-6 helped a lot with performance on odroid n2 (aarch64)

**Comment by MastaG** [comment]
@barbudreadmon 
I'm running Fedora 30 (beta) for arm 32bit on my Odroid XU3 and XU4.
Together with gnome 3.32 and the mali r14p1 drivers from arm which supports both wayland and drm.

llvm/clang 8.0 will be part of Fedora 30 so they're in the repository.
I'm building natively on the odroid itself.

But llvm/clang doesn't require you to setup a cross-compiler toolchain.
You can just install it on your ubuntu 18.04 desktop and tell it to build for aarch64.
See: https://apt.llvm.org/ they already have a branch for version 8.0

deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main
deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main

**Comment by barbudreadmon** [comment]
> See: https://apt.llvm.org/ they already have a branch for version 8.0

I already checked this one, no package provided for aarch64 though.
Thanks for the informations :)

**Comment by MastaG** [comment]
@barbudreadmon 
Oh, you're running 18.04 on your N2 and building it natively as well?
In that case you'll have a hard time finding a repository providing precompiled aarch64 packages for llvm/clang 8.0.

But you can just install the https://apt.llvm.org/ repository on your ubuntu x86_64 installation and tell it to build reicast for aarch64.

Or you can manually compile llvm/clang 8.0 on your odroid N2 :)

**Comment by flyinghead** [comment]
The change in `core/rec-ARM/rec_arm.cpp` should be fine: the clang `__builtin___clear_cache` expects `char *` arguments where gcc expects `void *`. But the former converts implicitly to the latter.

**Comment by MastaG** [comment]
Thanks @flyinghead

@twinaphex
Could you please merge it? :)

**Comment by blisstik** [comment]
What game are you using to benchmark? Virtua Tennis 2 for DC? And what device, XU4?

**Pull request merged**
