### PR TITLE
add options to display VMU screens

### PR DESCRIPTION
**Pull request by RetroSven**

### CODE REVIEW

**Comment by inactive123** [comment]
Hey man, that's awesome of you, thanks for adding that!

I am sure @flyinghead will be very happy to see this too.

**Comment by flyinghead** [comment]
Fantastic! Thanks for your help

**Comment by inactive123** [comment]
I see the VMU screen only very briefly at the Sega Enterprises screen, and then rarely ever again.

Tested this with the Reicast OIT core.

**Comment by inactive123** [comment]
It seems it works properly with the non-OIT core. So it seems the major rendering issues are only with the OIT core. Perhaps something for @flyinghead to look into?

**Comment by RetroSven** [comment]
I cannot run the OIT version - lack the hardware requirements - so unfortunately cannot really diagnose.

**Comment by Shoegzer** [comment]
@RetroSven thanks so much for this very nice feature!  I'm willing to help test OIT as I use that core, in case it might be of benefit.  

Two other questions that come to mind:

1) Can the VMU be displayed outside the game area when played in native dreamcast 4:3 resolution?

2) Is there a way to play VMU mini-games in "standalone" without actually launching a dreamcast game?

**Comment by RetroSven** [comment]
@Shoegzer not at this time

**Comment by Shoegzer** [comment]
@RetroSven I assume that applies for all of the above, and that's okay.  I was curious and hopeful, but also practical as I'm not sure how much time you can offer to the project.  Thanks again for your great VMU contributions, Sven.

**Pull request merged**
