### PR TITLE
throttling

### PR DESCRIPTION
**Pull request by RetroSven**
one more time

### CODE REVIEW

**Comment by inactive123** [comment]
OK, so just to confirm, when threaded rendering is enabled, we can still fastforward now?

**Comment by inactive123** [comment]
I still cannot fastforward with threaded rendering turned off.

**Comment by inactive123** [comment]
Can't fastforward with threaded rendering enabled either. Does this actually fix anything? Are you testing this on PC/Windows?

**Comment by RetroSven** [comment]
The fix was mostly to just ensure the recent changes only affect/are run when in threaded rendering mode.

Did fast forward previously work with both threaded rendering enabled and disabled?

**Comment by inactive123** [comment]
Fastforward worked fine before with threaded rendering disabled.

I have no idea about threaded rendering, I believe it did but I am not sure.

In any case, this absolutely has to work. And it absolutely should not require any changes to RetroArch at all. This is a deficiency on the core side, not RetroArch.

**Comment by inactive123** [comment]
BTW, in case you don't know, you can toggle fastforwarding by pressing the Spacebar key on your keyboard.

**Comment by inactive123** [comment]
This commit -

commit f78e308154019d2ff5ea8629fd232914fd751681 (HEAD)
Author: Sven <40953353+RetroSven@users.noreply.github.com>
Date:   Tue Sep 4 00:01:58 2018 -0400

    fix cpu unthrottling

Definitely broke fastforwarding. Ever since, fastforwarding is no longer working.

**Comment by inactive123** [comment]
This is still an issue unfortunately, and it's a pretty bad issue at that. Are we stuck here implementing this properly?

**Comment by RetroSven** [comment]
@twinaphex please see my comments on https://github.com/libretro/reicast-emulator/pull/247

**Pull request merged**
