### PR TITLE
implement save states

### PR DESCRIPTION
**Pull request by RetroSven**
implement save states
note - does not currently work with the new threaded rendering mode
seems to work ok on linux and windows, but have not tested more than a couple of games - so needs more testing

### CODE REVIEW

**Comment by inactive123** [comment]
Awesome commit @RetroSven!

@flyinghead This is something where @RetroSven could definitely need your help with - with regards to 'does not currently work with the new threaded rendering mode'.

**Comment by inactive123** [comment]
@RetroSven 

Just tried it real quick on Windows.

1) There is a lot of excess printf logging in serialize.cpp that makes it very slow right now. You might want to #if 0 that out.
2) It seems to get stuck in a loop and it never returns again to the game when trying to savestate. RetroArch then has to be manually closed since it is no longer responding. Tried with DOA2 and then Power Stone. Same thing.

**Comment by RetroSven** [comment]
printf's removed - didn't notice they were still in there

re: loop - odd - can you post a log?  Maybe there's something where is the save state doesn't return fast enough it tries again.  Are you testing on a fast system?

re: threaded - @flyinghead I believe all I'll need to do is disable the thread processing while saving/loading states.  Sound right to you?

**Comment by RetroSven** [comment]
I just tried power stone - worked fine for me.  Can you send your cfg settings for RA and for reicast?  Have you changed any of the defaults?

**Comment by inactive123** [comment]
retroarch.cfg -

https://hastebin.com/wijesoruqe.ini

retroarch-core-options.cfg -

https://hastebin.com/lewotufuta.ini

**Comment by flyinghead** [comment]
@RetroSven, the emulation thread should be stopped (dc_stop() before state loading and saving. Then there shouldn’t be any difference between threaded and non-threaded

**Comment by RetroSven** [comment]
@twinaphex have you tried the non-OIT version?

most recent PR now has working threaded mode

**Comment by RetroSven** [comment]
Also, is that your full reicast cfg?  I seem to have many more options like:

reicast_render_to_texture_upscaling = "1x"
reicast_system = "auto"
reicast_texupscale = "off"
reicast_texupscale_max_filtered_texture_size = "256"
reicast_threaded_rendering = "enabled"
reicast_trigger_deadzone = "0%"
reicast_volume_modifier_enable = "enabled"
reicast_widescreen_hack = "disabled"

**Comment by flyinghead** [comment]
I've only done light testing but so far it works fine for all the games I tried. Very impressive!

I've noticed an issue with fog. The variable `fog_needs_update`should not be serialized and forced to true when unserializing to force updating the fog texture on the GPU.

**Comment by RetroSven** [comment]
@flyinghead  I was just looking at that because I was noticing something like that myself during loading of power stone save state - it looked a little off - thanks for helping to zone in on that - it works - creating PR
Thanks

**Pull request merged**
