### PR TITLE
Naomi: M2 mame rom support

### PR DESCRIPTION
**Pull request by flyinghead**
Support loading mame rom in .zip format.
Only Naomi M2-type cartridge are currently supported.

### CODE REVIEW

**Comment by barbudreadmon** [comment]
@p1pkin it seems we are having issues getting M1 roms to work, however @flyinghead ported mame's code for those and it seems to be working properly (he compared the decrypted output), is it working in mame ? It seems M1 games hang on mame, and we get opcode errors in reicast. Any help would be appreciated.

**Comment by flyinghead** [comment]
I figured it out: there was an endianness problem with the key.
But it seems M1 carts don't load in mame because of this: the key needs to be byte-swapped

**Comment by barbudreadmon** [comment]
@flyinghead Nice !

**Comment by p1pkin** [comment]
nice find, thanks!

**Pull request merged**
