### PR TITLE
(libretro) Update libretro-common + various fixes

### PR DESCRIPTION
**Pull request by barbudreadmon**

### CODE REVIEW

**Review by flyinghead — APPROVED** [review]

**Comment by 5schatten** [comment]
This update fixes builds for libmali based projects (RK3399) but now platform RPi2 fails:

https://pastebin.com/xNxZgKfs

**Comment by barbudreadmon** [comment]
Ok, i guess all rpis are missing this def then, fixed in my next commit

**Comment by barbudreadmon** [comment]
@5schatten there were still a few mistakes, it _should_ be ok now

**Comment by 5schatten** [comment]
@barbudreadmon builds fine now for RPi2 :+1:

**Pull request merged**
