### PR TITLE
extra_depth_scale was reset to 1 during startup and ignored for large Z values

### PR DESCRIPTION
**Pull request by flyinghead**

### CODE REVIEW

**Comment by RetroSven** [comment]
@flyinghead I'm trying to draw a texture on the screen at an x,y coordinate, but I've never worked with opengl before.  I'm confident I've got the texture/data created fine since I've done that before in other graphics libs, but everything I've tried to get it on the screen seems to just do nothing.  Perhaps I'm not invoking the display code in the right place (i.e. maybe it's getting drawn but then overwritten by the main screen) or (more likely) what I'm doing to display is wrong somehow.  I've used several different examples from the internet and most recently tried re-using much of the code in gldraw.cpp:DrawFramebuffer.  Do you have any suggestions on what to leverage in the existing code to just draw a texture at x,y on top of the main screen?

**Comment by flyinghead** [comment]
It could be the coordinates transformation that isn't right. In reicast, everything is done in screen coordinates (0,0 -> 640,480 in most cases) and in DrawFramebuffer Z is set to 1 (the depth of the screen).
In the normalized opengl coordinates, x,y and z are in the 0..1 range and Z=1 means infinite depth (the opposite of dreamcast).
Try to set your depth to 0 to see if it helps.

**Comment by RetroSven** [comment]
Unfortunately z=0 didn't work.  I've tried calling the following right after UpdateFogTexture() and also right near the end of RenderFrame(), but haven't been able to make anything show up on the screen.  Will you please take a quick look to see if anything stands out as being wrong to you?

https://pastebin.com/0YwWPFGx

(in the code, I also tried replacing the .50 and .75 coordinate values with something like 300 and 200)

**Comment by flyinghead** [comment]
@RetroSven I took your code and with minor modifications I was able to run it in my branch.

https://pastebin.com/pSrSWcQw

I just had to change the vertex coordinates to dreamcast screen coordinates and set the depth back to 1 (screen depth).
The last two glBufferData() calls restore the normal data buffers and are needed only if drawing other primitives in the current frame after the call.

I'm calling your function at the end of DrawStrips() so it's drawn on top of the normal DC screen.

**Comment by flyinghead** [comment]
It should look like this:
retrosven

**Comment by RetroSven** [comment]
@flyinghead excellent that works - thanks much!  
(although I'm upset with myself that I was so close to the solution and it turned out to be just the coordinates plus some extraneous stuff - when I was playing with values between 0x0-640x480 I must have mucked them up somehow and perhaps they manifested as 0-width lines or something)

**Comment by flyinghead** [comment]
Debugging OpenGL is really a pain. It's the first time in my career that I sometimes resort to trying random, or blatantly wrong changes, that lead me to the solution.

**Comment by blisstik** [comment]
What does extra depth fix?

________________________________

**Comment by inactive123** [comment]
@6alileo It fixes the graphics in Samurai Shodown 6 (Naomi game). For all other games, you should turn it off for now.

At least based on my limited tests.

**Comment by blisstik** [comment]
Got it. Is this or will it be a hidden core option?

________________________________

**Pull request merged**
