### PR TITLE
Rebase rec-ARM:

### PR DESCRIPTION
**Pull request by inactive123**
* Update to latest files
* Rename rec-ARM to arm_emitter

### CODE REVIEW

**Comment by inactive123** [comment]
Approved by @flyinghead.

**Comment by cmitu** [comment]
The changes break the build for ARM systems - https://git.libretro.com/libretro/flycast/-/jobs/176164/raw.

**Comment by inactive123** [comment]
Can you help us backporting this? For now I'll have to revert this I guess.

**Comment by bluestang2006** [comment]
> Can you help us backporting this? For now I'll have to revert this I guess.

Looks like this file needs updates - https://github.com/flyinghead/flycast/blob/master/core/hw/sh4/dyna/ngen.h

**Pull request merged**
