### PR TITLE
remove unnecessary audio blocking workaround code ; tell RA to save states in background as appropriate

### PR DESCRIPTION
**Pull request by RetroSven**

### CODE REVIEW

**Comment by inactive123** [comment]
> #define RETRO_ENVIRONMENT_SET_SAVE_STATE_IN_BACKGROUND RETRO_ENVIRONMENT_PRIVATE+1

Hmm, so you think making this a private environ callback might be best for now?

**Comment by inactive123** [comment]
Alright, let's try this for now.

**Comment by RetroSven** [comment]
yes it appears to be  RETRO_ENVIRONMENT_PRIVATE's purpose

**Comment by blackman91** [comment]
This one broke the core with threaded rendering enabled, now it has no sound and it runs too fast with tr enabled.

**Comment by RetroSven** [comment]
@blackman91 please double check that - note that you must be on the latest RA as well as the latest Reicast core.  Works fine here in threaded and non-threaded

**Comment by blackman91** [comment]
You were right RetroSven updating to latest nightly fixed the issue, save and loading states and fast forwarding is working perfectly now too, nice job.

**Pull request merged**
