### PR TITLE
Light Gun support

### PR DESCRIPTION
**Pull request by flyinghead**
Tested with:
* House of the Dead 2 (US and EU)
* Confidential Mission (EU)
* Death Crimson 2 (JP)

### CODE REVIEW

**Comment by inactive123** [comment]
Thanks a lot for this!

**Comment by blisstik** [comment]
Any USB gun or via analog stick?

**Comment by flyinghead** [comment]
Mouse or any pointing device that can return absolute screen coordinates.
Analog sticks are not supported for this function.

**Comment by ghost** [comment]
Does this work for NAOMI also?

**Comment by flyinghead** [comment]
Probably not but perhaps this can be improved

**Pull request merged**
