### PR TITLE
Correct last commit to disable LTO for ODroid XU3/4

### PR DESCRIPTION
**Pull request by MastaG**
This will hopefully stop the bugreports on segfaults.

### CODE REVIEW

**Comment by litaniast** [comment]
Thanks a lot, but please apply this in RockPro64.

**Comment by MastaG** [comment]
Well first verify that it fixes your problem issue.
Build flycast by adding: HAVE_LTCG=0 to your make command e.g.:
make platform=RK3288 HAVE_LTCG=0 ARCH=arm -j4

If that solves your issue, then perhaps it's a good idea to disable LTO on all arm platforms.

**Comment by litaniast** [comment]
I added the HAVE_LTCG=0 parameter in build script and it works on my RockPro64!

**Comment by MastaG** [comment]
Thanks for testing!

@flyinghead don't merge yet.
I'll add another commit to disable LTO on all arm platforms

**Comment by mrcmunir** [comment]
hmmm If Disable Lto Will break nVIDIA jetson nano build with linker .
No crash here.

**Comment by MastaG** [comment]
I don't think disabling LTO could 'break' things. Only the resulting binary would be slightly larger.
But nVidia Jetson is arm64 right?
I was only going to disable it for armv7 (e.g. 32bit).

**Comment by mrcmunir** [comment]
> I don't think disabling LTO could 'break' things. Only the resulting binary would be slightly larger.
> But nVidia Jetson is arm64 right?
> I was only going to disable it for armv7 (e.g. 32bit).

Oh it's just for 32bit ok
Yes Nvidia jetson nano is arm64 (I just tried it now when I've had a while to do it) Everything correct is not affected by the change
I said this because in the past I had some problems linking without lto.

**Comment by litaniast** [comment]
This commit only fixed in odroid, not yet in rockpro64

**Pull request merged**
