### PR TITLE
Draw a HOTD2 look-a-like gunsight.

### PR DESCRIPTION
**Pull request by r3tro80**
Redrawn of the gunsight to be more like the original HOTD2 dreamcast version gunsight...

### CODE REVIEW

**Comment by flyinghead** [comment]
It's a matter of taste but I think I prefer the previous version. @hiddenasbestos did the first gunsight PR and he may have an opinion as well.

Perhaps a new core option could be added to let the user choose the gunsight type?

**Comment by hiddenasbestos** [comment]
An option makes sense I suppose, and would be easy enough to add. I don't have strong feelings about it really but there are more games than HOTD2 so it's only a look-a-like for that game.

**Comment by r3tro80** [comment]
There's already an option to select the gunsight color, another option to select gunsight type would be great! We can add a list of gunsights taken from the various dreamcast games.

**Comment by barbudreadmon** [comment]
To my knowledge, the more there are core options, the more it'll become an issue with savestates-based netplay (it might not be an issue atm, but what about the future ?), and the more people will feel lost when setting the core.
Just throwing this idea : maybe gunsight and gunsight customization could be implemented 100% frontend-side ?

**Comment by hiddenasbestos** [comment]
> To my knowledge, the more there are core options, the more it'll become an issue with savestates-based netplay (it might not be an issue atm, but what about the future ?), and the more people will feel lost when setting the core.
> Just throwing this idea : maybe gunsight and gunsight customization could be implemented 100% frontend-side ?

Front end doing this makes a lot of sense in terms of consistency and core simplication, but I don't think there's anyone gonna actually implement it. So we end up with this as a solution roughly duplicated for each core.

**Comment by inactive123** [comment]
Hmm, maybe we should reconsider this guys and maybe add it after all? It could be good as an option, it doesn't have to completely replace the existing pointer, just as a core option to be able to switch between the two.

While the frontend idea is nice, the reality is that we are nowhere near there yet for something like that and this could be a good stopgap solution in the meantime that also works for other fronts.

**Pull request closed without merging**
