### PR TITLE
Crc matching

### PR DESCRIPTION
**Pull request by barbudreadmon**
Missing the additional function for 7z (currently it's always returning `NULL`), we can either merge this as-is, or wait for a 7z implementation of this function (i'll need help with this one).

MAME 0.214's `mvsc2u.zip` is now starting successfully.

### CODE REVIEW

**Comment by barbudreadmon** [comment]
The only stuff remaining would be to add all real crcs, however i won't do it right now (i'll probably add some from time to time though).
This PR is ready to merge.

**Review by flyinghead — APPROVED** [review]
Great!

**Comment by Shoegzer** [comment]
@barbudreadmon Thanks for this.  While you're looking into this, any chance you could add the good flash file dump as per https://github.com/libretro/flycast/issues/99 ?

**Comment by barbudreadmon** [comment]
@Shoegzer Not sure i understand your request, if it's about updating the info file, that's useless, md5 in info files are only there to mention a bios supposedly working.

**Comment by Shoegzer** [comment]
@barbudreadmon I realize retroarch/flycast doesn't actually enforce good dumps of the flash file, but that doesn't mean it's useless.  Anyone needing to manually check their flash file against the retroarch MD5 will see the hash of an old and bad dump.  It would merely take a quick .info update of the hash value to reflect the new flash dump which is supported in MAME.  Ideally of course RA/flycast should throw a warning to the user that the dump is bad if the hash doesn't match, but that's a different feature entirely.

**Comment by barbudreadmon** [comment]
> MD5 will see the hash of an old and bad dump

1. There is absolutely no issue with current one
2. The new is bad too
3. I wouldn't recommend any of those 2 dumps anyway
4. For reminder you are supposed to dump the bios of your own console (http://www.dcdev.org/howtos/dump-bios.htm)

> Ideally of course RA/flycast should throw a warning to the user that the dump is bad if the hash doesn't match

What an horrible idea, let's hope it never happens, the core should always be the one to check for file sanity, i would gladly trade all the current firmware information in .info files for better tools to warn the user at the core level when there is actually an issue. 

If you want to send a PR to libretro-super, do it, don't ask me to send it in your stead, i won't.

**Comment by Shoegzer** [comment]
1. Well yes, there is an issue.  It's a _bad dump_ - but see # 2 below.
2. Actually you _were_ correct, that _was_ the case but very recently the MAME team replaced the second bad dump with the known good one (I just updated the issue summary to reflect this).
3. Right, because they were both bad, but again the new one is good.  I still would have recommended the second one anyway because at least it would be consistent with MAME.
4. Obviously you dump your own bios, which is exactly my point of why having a good hash value is quite handy.  In this case the flash file you dump isn't the "bios" strictly speaking but the idea is the same - once you dump the flash, it sure would be nice to have a handy reference that points to something known to be _good_, rather than something known to be _bad_.  Pretty simple concept.

About your "let's hope it never happens" comment - I'll tell you what, let's leave emotion out of this, hope you agree there's no need for us to be anti-social with each other?  And by the way, we're both talking about the same thing i.e. file sanity checking, and I never said the core shouldn't be the one to check for file sanity - ideally it should.  And it would be great to have some method of warning the user if the file isn't a good dump.  This would avoid bad troubleshooting reports in the future and all sorts of other unpleasantries borne on users and devs alike, which is precisely why 30-year-old MAME is so particular about it.

In case you didn't know, while MAME firmware such as dc bios/flash is checked against an internal database, it does maintain an _external_ database of software hashes as seen [here](https://github.com/mamedev/mame/tree/master/hash), similar at least in concept to .info files even if the format is XML.   I can join some of the MAME folks to this discussion for comment on specific rationale but among other benefits this allows external collaborators to contribute more easily without diving into code.  Regardless, I do agree that it would be better in this case to follow MAME's method of internally checking the dc bios/flash given its "static" nature.

In any event, I'm surprised why it's such a big deal to change the hash value that's already there.  If we don't like how the info file system works (I'm not disagreeing with you) then fine, rip it out - but as long as it's there, and it doesn't take more than two seconds to update the info, you may as well add the known good dump.

**Comment by barbudreadmon** [comment]
> it doesn't take more than two seconds to update the info, you may as well add the known good dump.

Because i'm completely against having this stuff in info files in the first place, it's just an awful workaround to deal with the real issue (= not having ways to provide support messages to the user from the core, while the core is the only one that can do this sanity check properly). Why asking **me** instead of sending a PR yourself ? You are totally speaking to the wrong guy in the wrong topic here...

**Comment by Shoegzer** [comment]
Well as I said I agree with you on being against external info files, at least in cases like firmware, I just didn't figure it was a big deal to change given you were already looking at related issues like #704.  Since it's too much trouble then don't worry about it, I suppose I or the original .info creator or anyone really could submit a PR to change it.  By the way, since you mentioned "better tools" earlier, are you aware of any developments in this area to address this issue?  The MAME "one-time warning" system is a good one to pattern after I think.

**Comment by barbudreadmon** [comment]
I opened an issue about it some time ago : https://github.com/libretro/RetroArch/issues/9388 .
Also, i'm not an admin at https://github.com/libretro/libretro-super , so i open PRs in there only if there is a real need, which is definitely not the case here. And i don't think that's related to current PR at all, current PR was required to fix games like `mvsc2u` with MAME 0.214 romsets while keeping compatibility with older romsets.

**Comment by Shoegzer** [comment]
Ah, very good.  I think you nailed it with [#9388](https://github.com/libretro/RetroArch/issues/9388), pretty much on point with what I was thinking.  Also in case it helps, with MAME at least there's a subtle difference between a "good dump", a "bad dump" and the "best known" dump, where the latter is typically a hash placeholder until a better dump is made and to assist troubleshooting through standardization etc.  Also while I'm thinking about it, no "bad" firmware dump is ever intentional - there can be "good alternative" dumps where a firmware was customized etc., though I'd caution against cores whitelisting such things and support only offical firmware, to your point about minimizing troubleshooting headaches from users.  Anyway, we could continue the discussion on that issue thread in the future.  Thanks much for the feature request, I hope it gains traction.

Current PR is only related in the very loose sense of surrounding "CRCs and bios", that's it. ;)

**Pull request merged**
